"use client";

import React from "react";
import Link from "next/link";
import { AuthGuard } from "@/components/AuthGuard";
import { HRHeader } from "@/components/HRHeader";
import { ResponsibleAIView } from "@/components/ResponsibleAIView";

export default function HRResponsibleAIPage() {
  const statusCards = [
    {
      title: "Algorithmic Fairness",
      status: "ACTIVE",
      statusColor: "bg-emerald-50 text-emerald-800 border-emerald-200",
      indicatorColor: "bg-emerald-500",
      description: "Continuous disparate impact monitoring across gender, age, and regional cohorts with zero statistical divergence."
    },
    {
      title: "Workforce Privacy",
      status: "ACTIVE",
      statusColor: "bg-emerald-50 text-emerald-800 border-emerald-200",
      indicatorColor: "bg-emerald-500",
      description: "Strict aggregation thresholds. Zero individual keystroke, webcam, or intrusive surveillance telemetry collected."
    },
    {
      title: "Human Oversight",
      status: "REQUIRED",
      statusColor: "bg-blue-50 text-blue-800 border-blue-200",
      indicatorColor: "bg-blue-500",
      description: "Every AI insight serves as advisory decision support. Final decisions always mandate human HR verification."
    },
    {
      title: "Automated Rejection",
      status: "DISABLED",
      statusColor: "bg-rose-50 text-rose-800 border-rose-200",
      indicatorColor: "bg-rose-500",
      description: "Hard algorithmic disqualification is permanently disabled by policy across both candidate and HR modules."
    }
  ];

  const privacyGuidelines = [
    {
      label: "Zero Biometric or Keystroke Tracking",
      detail: "Telemetry strictly measures structured operational milestones (PR turnaround, sprint velocity, attendance punch-in/out). No continuous monitoring tools are deployed."
    },
    {
      label: "Data Minimization & Encryption",
      detail: "Personnel identifiers are encrypted at rest using AES-256 and transmitted exclusively via TLS 1.3. Telemetry aggregations are anonymized for departmental reporting."
    },
    {
      label: "Non-Punitive Telemetry Usage",
      detail: "Workforce strain indicators (burnout risk, late days) are designed to trigger managerial support and workload rebalancing—never punitive performance actions."
    },
    {
      label: "Auditability & Traceability",
      detail: "Every answer generated by the AI HR Desk is grounded in deterministic logs with an explicit Evidence Trail and Recommended Action chain."
    }
  ];

  return (
    <AuthGuard requiredRole="hr">
      <div className="flex flex-col min-h-screen bg-slate-50 text-slate-800">
        <HRHeader activeSection="responsible-ai" />

        <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 py-8 sm:py-10 space-y-8 animate-fade-in">
          {/* Header Banner */}
          <div className="bg-gradient-to-r from-slate-900 via-slate-900 to-[#0a0f1d] border border-slate-800 rounded-2xl p-6 sm:p-8 flex flex-col md:flex-row md:items-center justify-between gap-6 shadow-sm text-white">
            <div>
              <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-slate-800/80 border border-slate-700 text-[11px] font-semibold text-emerald-300 mb-3">
                <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse"></span>
                Ethical Governance &amp; Algorithmic Accountability
              </div>
              <h1 className="text-2xl sm:text-3xl font-extrabold text-white tracking-tight">
                Responsible AI &amp; Workforce Ethics
              </h1>
              <p className="text-xs sm:text-sm text-slate-300 mt-1 max-w-2xl leading-relaxed">
                CareerGPS operates under strict ethical guardrails to prevent algorithmic bias, eliminate automated disqualification, and protect employee privacy.
              </p>
            </div>

            <div className="flex items-center gap-3 shrink-0">
              <Link
                href="/hr/model-evaluation"
                className="px-4 py-2.5 rounded-xl bg-slate-800 hover:bg-slate-700 border border-slate-700 text-xs font-semibold text-slate-200 hover:text-white transition flex items-center gap-2 shadow-xs"
              >
                Inspect Cross-Validation CV Results ↗
              </Link>
            </div>
          </div>

          {/* 4 Status Cards */}
          <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {statusCards.map((card, i) => (
              <div
                key={i}
                className="bg-white border border-slate-200/80 rounded-2xl p-5 shadow-xs flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <span className="text-xs font-bold text-slate-900">{card.title}</span>
                    <span
                      className={`text-[10px] font-bold px-2 py-0.5 rounded-full border ${card.statusColor} font-mono`}
                    >
                      {card.status}
                    </span>
                  </div>
                  <p className="text-xs text-slate-600 leading-relaxed mb-4">
                    {card.description}
                  </p>
                </div>
                <div className="flex items-center gap-2 pt-2 border-t border-slate-100">
                  <span className={`w-2 h-2 rounded-full ${card.indicatorColor}`}></span>
                  <span className="text-[10px] font-mono font-medium text-slate-500 uppercase">
                    Guardrail Verified
                  </span>
                </div>
              </div>
            ))}
          </section>

          {/* Core Principles (from ResponsibleAIView) */}
          <ResponsibleAIView />

          {/* Data Protection Guidelines */}
          <section className="bg-white border border-slate-200/80 rounded-2xl p-6 sm:p-8 shadow-xs">
            <div className="inline-flex items-center gap-2 px-2.5 py-1 rounded-full bg-blue-50 border border-blue-200 text-[11px] font-semibold text-blue-700 mb-3">
              <span>🔒</span> DPDP &amp; GDPR Compliance Architecture
            </div>
            <h3 className="text-xl font-extrabold text-slate-900 tracking-tight mb-2">
              Workforce Data Protection &amp; Telemetry Guidelines
            </h3>
            <p className="text-xs sm:text-sm text-slate-600 mb-6 max-w-3xl leading-relaxed">
              Our workforce analytics prioritize human dignity and developmental support over invasive workplace monitoring.
            </p>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {privacyGuidelines.map((g, idx) => (
                <div
                  key={idx}
                  className="bg-slate-50/70 border border-slate-200/80 rounded-xl p-4 sm:p-5 shadow-xs"
                >
                  <h4 className="text-xs sm:text-sm font-bold text-slate-900 mb-1.5 flex items-center gap-2">
                    <span className="h-1.5 w-1.5 rounded-full bg-teal-600"></span>
                    {g.label}
                  </h4>
                  <p className="text-xs text-slate-600 leading-relaxed">
                    {g.detail}
                  </p>
                </div>
              ))}
            </div>
          </section>
        </main>
      </div>
    </AuthGuard>
  );
}
